LinkedIn profile Validator
boriskezikov/linkedinbot pull request #16
Opened 2023-01-16 20:38 UTC by IvanShitlin

rewrote regex which validate linkenin url so now it approve only linkedin profiles

2023-01-17 09:10 UTC, boriskezikov requested changes

2023-01-17 09:10 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/logic/LinkedInAccountService.java
> -        return linkedInUrl.replace("/mwlite", "");
а где тебе этот функционал будет? не вижу куда ты его передвинул. Замена mwlite

2023-01-18 09:54 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/logic/LinkedInAccountService.java
> -        return linkedInUrl.replace("/mwlite", "");
@IvanShitlin

2023-01-18 10:08 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/logic/LinkedInAccountService.java
> +                .map(linked -> linked.replace("/mwlite", ""))
@boriskezikov вот же он)

2023-01-18 10:42 UTC, boriskezikov approved these changes

2023-01-18 10:55 UTC, merged