Добавил возможность боту иметь состояния
boriskezikov/linkedinbot pull request #23
Opened 2023-01-20 12:58 UTC by IvanShitlin

Состояния позволяют реагировать на отправленное сообщение пользователем по-разному, по сути понимая контекст: к какой команде относится данное сообщение и что с ним делать.
Интерфейс `Interaction` определяет поведение бота на сообщение. В `InteractionConfiguration` настраиваются все интеракции, идет сопоставление состояния бота и реакции, которую он воспроизведет на сообщение

2023-01-22 09:56 UTC, boriskezikov requested changes

2023-01-22 09:56 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/commands/admin/CountCommand.java
> +        return "count";
сделай статик переменную финальную для этого если они одинаковые

2023-01-22 09:56 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/config/InteractionConfiguration.java
> +                                interaction -> interaction
Function.identity()

2023-01-22 09:56 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/logic/LinkedInBot.java
> +import com.tr.linkedinbot.commands.*;
avoid star imports

2023-01-22 09:56 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/logic/LinkedInBot.java
> +        commands.forEach(this::register);
порядок не важен?

2023-01-22 09:56 UTC, boriskezikov commented on src/main/java/com/tr/linkedinbot/repository/LinkedInProfileRepository.java
> +    Optional<LinkedInProfile> getByChatId(@Param(value = "chatId") Long chatId);
если юзаешь именную кверю @Param не нужен.

2023-01-22 10:03 UTC, boriskezikov approved these changes

2023-01-22 15:59 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/commands/admin/CountCommand.java
> +        return "count";
fixed

2023-01-22 16:00 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/config/InteractionConfiguration.java
> +                                interaction -> interaction
fixed

2023-01-22 16:00 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/logic/LinkedInBot.java
> +import com.tr.linkedinbot.commands.*;
fixed

2023-01-22 16:01 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/logic/LinkedInBot.java
> +        commands.forEach(this::register);
не, их нужно просто зарегать, есть команда registerAll(), но она принимает varagrs

2023-01-22 16:01 UTC, IvanShitlin commented on src/main/java/com/tr/linkedinbot/repository/LinkedInProfileRepository.java
> +    Optional<LinkedInProfile> getByChatId(@Param(value = "chatId") Long chatId);
fixed

2023-01-23 09:18 UTC, boriskezikov approved these changes

2023-01-23 13:08 UTC, merged